"""
Tests for the GCO MCP server's FastMCP transforms (mcp/server.py).

Covers the always-on Resources As Tools transform — the tool-only
clients (Cursor, etc.) reach resources through synthetic
``list_resources`` and ``read_resource`` tools generated by the
transform. The round-trip test confirms a resource registered against
a FastMCP instance with that transform is reachable through the
synthetic tool surface and returns the same payload the resource
handler does directly.

Also covers search-mode selection (BM25 default, regex, code_mode,
off, fallback for unknown values), Code Mode discovery-tool wiring,
audit-log experimental marker, and sandbox-limit env-var tunability.
"""

import asyncio
import importlib
import os
import sys
from pathlib import Path
from unittest.mock import patch

import pytest
from fastmcp import FastMCP
from fastmcp.server.transforms import ResourcesAsTools

# Ensure mcp/ is importable, mirroring tests/test_mcp_feature_flags.py.
sys.path.insert(0, str(Path(__file__).parent.parent / "mcp"))


@pytest.mark.asyncio
async def test_resources_as_tools_round_trip() -> None:
    """Synthetic ``read_resource`` returns the resource handler's payload.

    The Resources As Tools transform exposes a ``read_resource`` synthetic
    tool that proxies any registered resource. This test builds a fresh
    FastMCP instance with only that transform attached, registers a
    minimal resource, invokes the synthetic tool through ``call_tool``,
    and asserts the text payload matches the handler's direct return.

    Using a fresh instance (rather than the production ``mcp`` singleton
    from ``mcp/server.py``) keeps this test hermetic: nothing it
    registers leaks into other tests that count tools or resources on
    the live server.
    """
    test_mcp = FastMCP("transforms-roundtrip-test")
    test_mcp.add_transform(ResourcesAsTools(test_mcp))

    expected = "hello round trip"

    @test_mcp.resource("test://gco/round-trip")
    async def _round_trip_resource() -> str:
        return expected

    # Sanity-check the handler returns what we expect when called directly.
    assert await _round_trip_resource() == expected

    result = await test_mcp.call_tool("read_resource", {"uri": "test://gco/round-trip"})

    # FastMCP's ToolResult exposes both ``content`` (a list of TextContent
    # items) and ``structured_content`` (a dict). Assert both shapes match
    # so a future change in either surface is caught by this test.
    assert result.content, "read_resource returned no content blocks"
    assert result.content[0].text == expected
    assert result.structured_content == {"result": expected}


# =============================================================================
# Tool Search filtering tests
# =============================================================================
#
# These tests reload ``mcp/server.py`` under different ``GCO_MCP_TOOL_SEARCH``
# values and assert the resulting ``list_tools()`` matches the configured
# transform mode. Reloading the server module is what triggers the transform
# wiring at import time, which is why every test patches ``os.environ`` first
# and then calls ``importlib.reload(server)`` (and ``run_mcp`` so the live
# tools and resources re-register against the freshly built FastMCP instance).


def _reload_mcp_with_env(env: dict[str, str]) -> object:
    """Reload ``mcp.server`` and every ``mcp.tools.*`` / ``mcp.resources.*`` module.

    Reloading ``server`` is what re-runs the transform-wiring block (which
    reads ``GCO_MCP_TOOL_SEARCH`` from env at module-import time). Reloading
    every tool and resource module afterward forces their ``@mcp.tool`` /
    ``@mcp.resource`` decorators to re-bind to the freshly built FastMCP
    instance — without that, the new instance is empty and the listing
    only contains the synthetic transform tools.

    Returns the live ``mcp`` FastMCP instance attached to ``run_mcp.mcp``
    after the reload. Caller is responsible for restoring the env via the
    surrounding ``patch.dict`` context manager.
    """
    import run_mcp
    import server

    # Drop cached tools.* and resources.* modules so the freshly reloaded
    # ``server`` builds a clean FastMCP and every decorator re-fires.
    cached_submodules = [
        name
        for name in list(sys.modules)
        if name.startswith("tools.")
        or name.startswith("resources.")
        or name in ("tools", "resources")
    ]
    for name in cached_submodules:
        sys.modules.pop(name, None)

    importlib.reload(server)
    importlib.reload(run_mcp)
    return run_mcp.mcp


def _list_tool_names_via_public_api(mcp_instance: object) -> list[str]:
    """Return the names a client would see via ``mcp.list_tools()``.

    Uses the public coroutine (which runs through the transform pipeline)
    rather than ``_list_tools()`` (which bypasses transforms). The public
    surface is what the search-mode behaviour tests care about.
    """
    tools = asyncio.run(mcp_instance.list_tools())
    return [t.name for t in tools]


# Sentinel marker — once ``delete_inference`` is gated behind
# ``GCO_ENABLE_DESTRUCTIVE_OPERATIONS``, drop the skip and these tests run
# on every CI build.
_DESTRUCTIVE_GATING_PENDING = "delete_inference is not yet gated behind GCO_ENABLE_DESTRUCTIVE_OPERATIONS — skip until that gating lands"


@pytest.mark.skip(reason=_DESTRUCTIVE_GATING_PENDING)
def test_search_tools_filters_gated_tools() -> None:
    """Under default (bm25) + clean env, ``search_tools(query="delete_inference")`` returns ``[]``.

    The premise is that ``delete_inference`` is registered only when the
    destructive-operations flag is set, so a search against a clean
    environment finds nothing matching that query.
    """
    clean_env = {"GCO_MCP_TOOL_SEARCH": "bm25"}
    for var in (
        "GCO_ENABLE_DESTRUCTIVE_OPERATIONS",
        "GCO_ENABLE_ALL_TOOLS",
    ):
        os.environ.pop(var, None)
    with patch.dict(os.environ, clean_env, clear=False):
        mcp_instance = _reload_mcp_with_env(clean_env)
        result = asyncio.run(mcp_instance.call_tool("search_tools", {"query": "delete_inference"}))
    matches = result.structured_content.get("result", [])
    assert matches == [], f"expected empty results for gated tool under clean env, got {matches!r}"


@pytest.mark.skip(reason=_DESTRUCTIVE_GATING_PENDING)
def test_search_tools_returns_results_under_flag() -> None:
    """Under ``GCO_ENABLE_DESTRUCTIVE_OPERATIONS=true``, ``delete_inference`` shows up in search.

    Mirror of :func:`test_search_tools_filters_gated_tools` — same query,
    flag flipped on, result is now non-empty and contains the tool.
    """
    env = {
        "GCO_MCP_TOOL_SEARCH": "bm25",
        "GCO_ENABLE_DESTRUCTIVE_OPERATIONS": "true",
    }
    with patch.dict(os.environ, env, clear=False):
        mcp_instance = _reload_mcp_with_env(env)
        result = asyncio.run(mcp_instance.call_tool("search_tools", {"query": "delete_inference"}))
    matches = result.structured_content.get("result", [])
    names = [m["name"] for m in matches]
    assert "delete_inference" in names, (
        f"expected 'delete_inference' in search results under flag, got {names!r}"
    )


@pytest.mark.skip(
    reason="BM25SearchTransform.search_tools does not expose a 'tags' parameter on this FastMCP version — only the experimental Code Mode 'search' tool supports tag filtering"
)
def test_search_tools_filters_by_tag() -> None:
    """Search restricted to ``{"safe","examples"}`` returns only safe-examples tools."""
    env = {"GCO_MCP_TOOL_SEARCH": "bm25"}
    with patch.dict(os.environ, env, clear=False):
        mcp_instance = _reload_mcp_with_env(env)
        result = asyncio.run(
            mcp_instance.call_tool(
                "search_tools",
                {"query": "examples", "tags": ["safe", "examples"]},
            )
        )
    matches = result.structured_content.get("result", [])
    for m in matches:
        tag_set = set(m.get("meta", {}).get("fastmcp", {}).get("tags", []))
        assert tag_set & {"safe", "examples"}, (
            f"expected match to carry safe/examples tags, got {tag_set!r}"
        )


def test_always_visible_tools_appear_in_listing() -> None:
    """Under bm25, ``list_tools()`` includes the five pinned tools, search synthetics, and resource synthetics."""
    env = {"GCO_MCP_TOOL_SEARCH": "bm25"}
    for var in ("GCO_ENABLE_ALL_TOOLS", "GCO_ENABLE_DESTRUCTIVE_OPERATIONS"):
        os.environ.pop(var, None)
    with patch.dict(os.environ, env, clear=False):
        mcp_instance = _reload_mcp_with_env(env)
        names = set(_list_tool_names_via_public_api(mcp_instance))

    expected_pinned = {
        "find_examples",
        "find_docs",
        "list_jobs",
        "submit_job_sqs",
        "list_inference_endpoints",
    }
    expected_search_synthetics = {"search_tools", "call_tool"}
    expected_resource_synthetics = {"list_resources", "read_resource"}

    missing = (expected_pinned | expected_search_synthetics | expected_resource_synthetics) - names
    assert not missing, f"expected pinned/synthetic tools missing from listing: {missing!r}"


def test_default_env_uses_bm25() -> None:
    """With no ``GCO_MCP_TOOL_SEARCH`` set, the default is BM25 — the listing is the search-mode shape."""
    for var in (
        "GCO_MCP_TOOL_SEARCH",
        "GCO_ENABLE_ALL_TOOLS",
        "GCO_ENABLE_DESTRUCTIVE_OPERATIONS",
    ):
        os.environ.pop(var, None)
    mcp_instance = _reload_mcp_with_env({})
    names = set(_list_tool_names_via_public_api(mcp_instance))

    # BM25 mode produces a small, fixed-shape listing (≤ ~10 entries):
    # five pinned tools + search_tools/call_tool + list_resources/read_resource.
    # The full catalog under "off" mode runs into the 90s — assert against
    # both the synthetic-tools presence and the absence of representative
    # full-catalog entries to confirm BM25 is what's wired.
    assert "search_tools" in names, "expected BM25 search synthetic in default-env listing"
    assert "call_tool" in names, "expected BM25 call_tool synthetic in default-env listing"
    # Tools that aren't on the always-visible list shouldn't appear.
    assert "list_stacks" not in names, (
        "default-env listing should be BM25-mode (catalog-replaced), not legacy full catalog"
    )
    assert "cost_summary" not in names, (
        "default-env listing should be BM25-mode (catalog-replaced), not legacy full catalog"
    )


def test_search_off_returns_full_catalog() -> None:
    """Under ``GCO_MCP_TOOL_SEARCH=off``, the listing is the full catalog with no synthetics."""
    env = {"GCO_MCP_TOOL_SEARCH": "off"}
    with patch.dict(os.environ, env, clear=False):
        mcp_instance = _reload_mcp_with_env(env)
        names = set(_list_tool_names_via_public_api(mcp_instance))

    # No search synthetics in off-mode.
    assert "search_tools" not in names, "off-mode should not register the BM25 search synthetic"
    assert "call_tool" not in names, "off-mode should not register the BM25 call_tool synthetic"
    # Real tools are visible — pick representatives from each of the major domains.
    for real_tool in (
        "list_jobs",
        "list_stacks",
        "cost_summary",
        "list_inference_endpoints",
        "list_models",
    ):
        assert real_tool in names, f"off-mode should expose the full catalog; missing {real_tool!r}"
    # Resource-as-tools synthetics still register because the transform sits
    # below the catalog-replacement layer.
    assert "list_resources" in names
    assert "read_resource" in names


def test_unknown_tool_search_value_falls_back_to_bm25() -> None:
    """An unrecognised value for ``GCO_MCP_TOOL_SEARCH`` (e.g. ``banana``) falls back to BM25."""
    env_unknown = {"GCO_MCP_TOOL_SEARCH": "banana"}
    env_bm25 = {"GCO_MCP_TOOL_SEARCH": "bm25"}
    for var in ("GCO_ENABLE_ALL_TOOLS", "GCO_ENABLE_DESTRUCTIVE_OPERATIONS"):
        os.environ.pop(var, None)

    with patch.dict(os.environ, env_unknown, clear=False):
        mcp_unknown = _reload_mcp_with_env(env_unknown)
        names_unknown = set(_list_tool_names_via_public_api(mcp_unknown))

    with patch.dict(os.environ, env_bm25, clear=False):
        mcp_bm25 = _reload_mcp_with_env(env_bm25)
        names_bm25 = set(_list_tool_names_via_public_api(mcp_bm25))

    assert names_unknown == names_bm25, (
        f"unknown tool-search value should fall back to bm25 listing; "
        f"diff: {names_unknown ^ names_bm25!r}"
    )


# =============================================================================
# Code Mode wiring and replacement-behavior tests
# =============================================================================


def test_code_mode_replaces_catalog() -> None:
    """Under ``code_mode``, ``list_tools()`` exposes only the Code Mode meta-tools + resource synthetics."""
    env = {"GCO_MCP_TOOL_SEARCH": "code_mode"}
    with patch.dict(os.environ, env, clear=False):
        mcp_instance = _reload_mcp_with_env(env)
        names = set(_list_tool_names_via_public_api(mcp_instance))

    # Code Mode discovery + execute meta-tools must all be present. The
    # default tool names from FastMCP's experimental Code Mode classes are
    # ``tags`` (GetTags), ``search`` (Search), ``get_schema`` (GetSchemas),
    # and ``execute`` (CodeMode itself).
    for meta in ("search", "get_schema", "execute"):
        assert meta in names, f"expected Code Mode meta-tool {meta!r} in listing"

    # ResourcesAsTools sits below the catalog-replacement layer so its
    # synthetic tools survive the Code Mode replacement.
    assert "list_resources" in names
    assert "read_resource" in names

    # Original tool names must NOT appear directly — Code Mode replaced the
    # catalog with the meta-tool surface.
    for original in ("list_jobs", "find_examples", "cost_summary", "list_models"):
        assert original not in names, (
            f"expected original tool {original!r} to be replaced by Code Mode meta-tools"
        )


def test_code_mode_uses_four_stage_discovery() -> None:
    """Code Mode is constructed with ``[GetTags, Search, GetSchemas]`` discovery factories."""
    from fastmcp.experimental.transforms.code_mode import (
        CodeMode,
        GetSchemas,
        GetTags,
        Search,
    )

    env = {"GCO_MCP_TOOL_SEARCH": "code_mode"}
    with patch.dict(os.environ, env, clear=False):
        mcp_instance = _reload_mcp_with_env(env)
        attached = [t for t in mcp_instance.transforms if isinstance(t, CodeMode)]

    assert len(attached) == 1, (
        f"expected exactly one CodeMode transform attached, got {len(attached)}"
    )
    factories = list(attached[0]._discovery_factories)
    assert len(factories) == 3, f"expected 3 discovery factories, got {len(factories)}"
    assert isinstance(factories[0], GetTags), (
        f"first discovery factory should be GetTags, got {type(factories[0]).__name__}"
    )
    assert isinstance(factories[1], Search), (
        f"second discovery factory should be Search, got {type(factories[1]).__name__}"
    )
    assert isinstance(factories[2], GetSchemas), (
        f"third discovery factory should be GetSchemas, got {type(factories[2]).__name__}"
    )


def test_code_mode_audit_log_marks_experimental(caplog: pytest.LogCaptureFixture) -> None:
    """Under ``code_mode``, the startup audit entry has both ``tool_search`` and ``code_mode_experimental``."""
    import json
    import logging as _logging

    import audit

    env = {"GCO_MCP_TOOL_SEARCH": "code_mode"}
    with (
        patch.dict(os.environ, env, clear=False),
        caplog.at_level(_logging.INFO, logger="gco.mcp.audit"),
    ):
        # ``_resolve_tool_search`` reads ``GCO_MCP_TOOL_SEARCH`` from env on
        # every call, so no reload is needed — the patched env is enough.
        audit.emit_startup_log()

    startup_entries = [
        json.loads(rec.getMessage())
        for rec in caplog.records
        if rec.name == "gco.mcp.audit" and rec.getMessage().startswith("{")
    ]
    startup_entries = [e for e in startup_entries if e.get("event") == "mcp.server.startup"]
    assert startup_entries, "expected at least one mcp.server.startup audit entry"
    entry = startup_entries[-1]
    assert entry.get("tool_search") == "code_mode", (
        f"startup entry should record tool_search='code_mode', got {entry.get('tool_search')!r}"
    )
    assert entry.get("code_mode_experimental") is True, (
        f"startup entry should mark code_mode_experimental=True, got "
        f"{entry.get('code_mode_experimental')!r}"
    )


# =============================================================================
# Code Mode sandbox limits + env-var tunability tests
# =============================================================================


def _get_attached_code_mode() -> object:
    """Find the CodeMode transform on the live mcp instance (after a reload)."""
    import run_mcp
    from fastmcp.experimental.transforms.code_mode import CodeMode

    attached = [t for t in run_mcp.mcp.transforms if isinstance(t, CodeMode)]
    assert len(attached) == 1, (
        f"expected exactly one CodeMode transform attached, got {len(attached)}"
    )
    return attached[0]


def test_code_mode_sandbox_default_limits() -> None:
    """No env tuning → sandbox limits are 30s wall-clock / 200 MB memory."""
    env = {"GCO_MCP_TOOL_SEARCH": "code_mode"}
    for var in (
        "GCO_MCP_CODE_MODE_MAX_DURATION_SECS",
        "GCO_MCP_CODE_MODE_MAX_MEMORY",
    ):
        os.environ.pop(var, None)
    with patch.dict(os.environ, env, clear=False):
        _reload_mcp_with_env(env)
        cm = _get_attached_code_mode()

    from fastmcp.experimental.transforms.code_mode import MontySandboxProvider

    assert isinstance(cm.sandbox_provider, MontySandboxProvider), (
        f"expected MontySandboxProvider, got {type(cm.sandbox_provider).__name__}"
    )
    assert cm.sandbox_provider.limits == {
        "max_duration_secs": 30.0,
        "max_memory": 200_000_000,
    }


def test_code_mode_sandbox_limits_from_env() -> None:
    """``GCO_MCP_CODE_MODE_MAX_*`` env vars override the defaults."""
    env = {
        "GCO_MCP_TOOL_SEARCH": "code_mode",
        "GCO_MCP_CODE_MODE_MAX_DURATION_SECS": "5",
        "GCO_MCP_CODE_MODE_MAX_MEMORY": "50000000",
    }
    with patch.dict(os.environ, env, clear=False):
        _reload_mcp_with_env(env)
        cm = _get_attached_code_mode()

    assert cm.sandbox_provider.limits == {
        "max_duration_secs": 5.0,
        "max_memory": 50_000_000,
    }


def test_code_mode_sandbox_limits_invalid_env_falls_back() -> None:
    """Non-numeric or empty env values fall back to the defaults silently."""
    env = {
        "GCO_MCP_TOOL_SEARCH": "code_mode",
        "GCO_MCP_CODE_MODE_MAX_DURATION_SECS": "banana",
        "GCO_MCP_CODE_MODE_MAX_MEMORY": "",
    }
    with patch.dict(os.environ, env, clear=False):
        _reload_mcp_with_env(env)
        cm = _get_attached_code_mode()

    assert cm.sandbox_provider.limits == {
        "max_duration_secs": 30.0,
        "max_memory": 200_000_000,
    }
